package com.studcloud;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class SubjectAdd extends HttpServlet {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	//Database Connection Data
	String url,username,password;
	Connection con;
	
	@Override
	public void init(ServletConfig config) throws ServletException {
		// TODO Auto-generated method stub
		super.init(config);
		ConnectionOne condet=new ConnectionOne();
		url=condet.getUrl();
		username=condet.getUnm();
		password=condet.getPwd();
		try {
			Class.forName("com.mysql.jdbc.Driver");
			System.out.print("Driver Loaded...");
			con=DriverManager.getConnection(url,username,password);
			System.out.print("Connection Successful..");
		}catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			}
	}//end init
	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		//System.out.println("In doGet()");
		doPost(request, response);
			}//end doGet
	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		System.out.println("In doPost()");
		Statement st=null;
		ResultSet rs=null;
		// User Login Data //
		/*String usernm=request.getParameter("username");
		String pass=request.getParameter("pass");
		System.out.println("Username:-"+usernm);
		System.out.println("Password:-"+pass);*/
		
		String subid,standard,subject,subaddOn,subaddBy,opert,category;
		
		subid=request.getParameter("subid");
		standard=request.getParameter("stdh");
		subject=request.getParameter("subject");
		subaddOn="13-09-13";
		subaddBy="admin";
		opert=request.getParameter("operation");
		category=request.getParameter("catg");
		// Standard Code as it is: 01,02,03,04 etc.
		// School Code as it is 101,102,...etc.
		// Student code as it is schoolcode+stdcode+studentcode ie 001(AutoGenerated)=10101001
		//studcode=request.getParameter("tostd");
		//schoolcode=request.getParameter("contactPerson");
		//registerOn=request.getParameter("");
		//registerBy=request.getParameter("");
		
		
		
		PrintWriter pr=response.getWriter();
		RequestDispatcher rd;
		try {
				st=con.createStatement();
				if(opert.equals("add"))
				{
						System.out.println("******Insert Query in SubjectAdd******");
						int rowcount=st.executeUpdate("insert into studcloud.subjectlist(subject,standard,subAddOn,subAddBy,category)values('"+subject+"','"+standard+"','"+subaddOn+"','"+subaddBy+"','"+category+"')");
						System.out.println("Record Inserted into subjectlist table.... Subject Added Successfully..! "+rowcount);
						rd=request.getRequestDispatcher("SubjectAdd.jsp");
						rd.forward(request,response);
				}			
				if(opert.equals("edit"))
				{
						System.out.println("******Update Query in Tab Registration******");
						int rowcount1=st.executeUpdate("UPDATE studcloud.subjectlist SET subject='"+subject+"',standard='"+standard+"',subAddOn='"+subaddOn+"',subAddBy='"+subaddBy+"' WHERE subid='"+subid+"';"); 
						System.out.println("Record UPDATED in subjectlist table..... "+rowcount1);
						rd=request.getRequestDispatcher("SubjectAdd.jsp");
						rd.forward(request,response);
				}
				if(opert.equals("delete"))
				{
						System.out.println("******Delete Query in Tab Registration******");
						int rowcount1=st.executeUpdate("DELETE FROM studcloud.subjectlist WHERE subid='"+subid+"';"); 
						System.out.println("Record DELETED in subjectlist table..... "+rowcount1);
						rd=request.getRequestDispatcher("SubjectAdd.jsp");
						rd.forward(request,response);
				}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("Invalid / Duplicate entry...");
			rd=request.getRequestDispatcher("tabReg.jsp");
			rd.forward(request,response);
		}
	}
}
